version: '3.8'

services:
  arsip_app_mysql:
    image: mysql:8.0
    restart: always
    platform: linux/arm64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: arsip-app
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql

  arsip_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - arsip_app_mysql
    volumes:
      - .:/var/www/html
